# Mission name
MISSION_NAME: 'hermes'

# Package name for mission 
MISSION_PKG: 'hermes_core'

# Incoming data bucket
INCOMING_BUCKET: 'swsoc-incoming'

# Instrument names used in the mission. 
# The names are used to dynamically import the instrument packages.
INSTR_NAMES: 
- 'eea'
- 'nemisis'
- 'merit'
- 'spani'

# Timestream region
TSD_REGION: 'us-east-1'