# Config file for the SDC AWS S3 Watcher Service

# User to run the SDC AWS S3 Watcher as
SDC_SYSTEM_USER: "dbarrous"
# S3 Bucket name to store the data
SDC_AWS_S3_BUCKET: "damian-sam"

# SQS Queue URL to get messages from
SDC_AWS_SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/123456789012/sdc-aws-s3-watcher"

# Path to download files to
# SDC_AWS_WATCH_PATH: "/home/dbarrous/dbarrous/testdir"

# # Timestream database name (Optional)
# SDC_AWS_TIMESTREAM_DB: "sdc_aws_fswatcher"

# # Timestream table name (Optional)
# SDC_AWS_TIMESTREAM_TABLE: "logs"

# AWS Profile to use for authentication (Optional)
# SDC_AWS_PROFILE: "smce-profile"

# Concurrent uploads to S3 (Optional)
# SDC_AWS_CONCURRENCY_LIMIT: "20"

# Delete files from S3 if they are deleted from the watch directory (Optional)
# SDC_AWS_ALLOW_DELETE: "False"